import Head from "next/head";

const Head = () => {
  return (
    <Head>
      <title>Passner</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
  );
};

export default Head;